### ISSUE TITLE
A few issues, and a request for help.

### ISSUE THREAD

**Issue by AssassinsLament** [kinecosystem/kin-sdk-unity#1]
There are a few issues where your examples on github here are not correctly capitalized and can cause confusion. "kinClient.getAccount" is one of them, I saw more but might be in the kin android sdk section. Also, in this unity section, you describe an "account.Activate" but I wasn't able to find that method, so was that removed from the sdk? I also couldn't find it being used on the demo example included in the unity asset.

Now, I am pretty new with unity and development in c# in general, so this is not an issue but more like a plea for help.  I was able to get the demo working, but of course I wanted to take all the pieces I need from the demo and incorporate it into a class for my project, but I was not able to get it to work right. I could see my public wallet address, etc but I was not able to get the Wallet Balance, nor was I able to send anything, nor was I check the status of the account. I ran the code, and it seems as if I'm not getting the callback reply. I enabled the listeners also, but get nothing back. And if I run the code again, I get an exception that the command is still in flight... I have checked and seem to have everything that was in "KinDemoUI" but I didn't use anything from "KinDemoUIBase" since I assumed that only dealt with the gui interface. What did I miss?

Also, is there a way to check the blockchain to see if we were able send/receive the transactions?

**Comment by andreaKin** [comment]
Hi @AssassinsLament , we will look at the documentation and try to make sure references to variables and objects in the code are capitalized appropriately. Please note that the Unity SDK is written in C#, but under the hood it uses the Android SDK, so maybe there is some confusion in some places that we'll try to clarify.

About your question on checking if transactions or other operations on the blockchain succeeded, please look at http://laboratory-testnet.kininfrastructure.com/#explorer?network=test, from there you can look at wallets, transactions and so on.

Please post some code snippets of the classes you're building or the calls you're making that are giving you problems and we'll try to help.

**Comment by AssassinsLament** [comment]
Thank you @andreaKin !

Hi @prime31 ,

here is a pastebin of my code:
https://pastebin.com/L0JS3ikQ

I'm basically not getting any call back, so I'm wondering what I'm missing. I tried to just copy everything from "KinDemoUI" and may have missed something.

**Comment by prime31** [comment]
From what I can tell, the code looks fine. Please include the full log output.

**Comment by AssassinsLament** [comment]
That's the thing, there is no output... it's like I'm not receiving the callback. : 

`02-13 21:21:30.491 9938-9963/com.infectedByte.KinSDK I/Unity: Get Status Clicked!
02-13 21:21:30.491 9938-9963/com.infectedByte.KinSDK I/Unity: 0
02-13 21:21:30.494 9938-9963/com.infectedByte.KinSDK I/Unity: 4`

Now if I reclick the buttons OnGetStatusClick() and OnGetBalanceClick(), I get : 

`02-13 21:22:12.596 9938-9963/com.infectedByte.KinSDK E/Unity: KinException: KinAccount request already in flight for this method. Wait for it to complete before requesting it again.
      at Kin.KinAccount.throwIfRequestInFlight (System.Collections.IDictionary dict) [0x00018] in <9574899896f84d5dba33f45509090a4a>:0 
      at Kin.KinAccount.GetStatus (System.Action`2[T1,T2] onComplete) [0x00000] in <9574899896f84d5dba33f45509090a4a>:0 
      at KinClass.GetKinAccountStatus () [0x0000a] in <e255d9e7a7aa46178c18a94cd6881390>:0 
      at KinClass.OnGetStatusClick () [0x0000a] in <e255d9e7a7aa46178c18a94cd6881390>:0 
      at UnityEngine.Events.InvokableCall.Invoke () [0x00011] in <c651486033b34c6aa0857cb621ef91a5>:0 
      at UnityEngine.Events.UnityEvent.Invoke () [0x00023] in <c651486033b34c6aa0857cb621ef91a5>:0 
      at UnityEngine.UI.Button.Press () [0x00027] in <60ad667bd87245889f8c05537e7ca715>:0 
      at UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) [0x00011] in <60ad667bd87245889f8c05537e7ca715>:0 
      at UnityEngine.EventSystems.ExecuteEvents.Execute `

**Comment by prime31** [comment]
Don't filter the logcat output. There will always be at least some indicator in there if you do not filter only Unity logs. The entirety of Android OS and all native code will not show up when you filter it.

**Comment by AssassinsLament** [comment]
https://pastebin.com/FzMe3c5S

**Comment by andreaKin** [comment]
Hey @prime31 can you touch base with @AssassinsLament ? It's been almost 2 weeks

**Comment by prime31** [comment]
I ran a test using the KinRoot class that you sent over and it works fine for me. I wired up a few buttons to call the KinRoot methods and everything returned as expected (log attached). I would recommend ensuring you don't have any firewall or other contraption between your device and the Kin servers. Using something like Charles to monitor the network traffic is also a good idea.

[Log.txt](https://github.com/kinecosystem/kin-sdk-unity/files/2899290/Log.txt)

**Comment by infectedByte** [comment]
Thanks for your reply. I don't know what went wrong, but as I started a brand new project, I was able to get the call backs I expected. So I'm not sure what happened the first go round but consider this closed. Thanks.

**Comment by AssassinsLament** [comment]
Thanks for your reply. I decided to start a new project and redid my code and although I didn't change anything, I am now getting the callbacks I was expecting. I'm still lost as to what went wrong the first time but everything is good now. Thanks for the time and consider this closed.
