### ISSUE TITLE
Kin Coin intrigate in unity game

### ISSUE THREAD

**Issue by QCKin** [kinecosystem/kin-sdk-unity#23]

**Comment by cohenalex** [comment]
Hi @QCKin can you give us more details what is the issue you are facing? 
Thanks!

**Comment by NGS99** [comment]
Based on the date, I believe its the following issue that was posted in Discord.
---start issue---
I am getting an error from PostProcessor.cs
The reason for this is that i don't have the IOS module installed and i do not wish to do so as i am not Building for that platform.  To solve the issue i have added #if UNITY_IOS at the start of the script and #endif on the end so it will only work when IOS module is installed.
It is a red error
Assets\Kin\Editor\PostProcessor.cs(5,19): error CS0234: The type or namespace name 'iOS' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)
This is the error you will get until you make the change above.
