### ISSUE TITLE
PostProcessor.cs missing reference when IOS Module not installed

### ISSUE THREAD

**Issue by djaydino** [kinecosystem/kin-sdk-unity#24]
Hi.
There is an error with PostProcessor.cs when The ios Module (unity) is not installed.

Error : Assets\Kin\Editor\PostProcessor.cs(5,19): error CS0234: The type or namespace name 'iOS' does not exist in the namespace 'UnityEditor' (are you missing an assembly reference?)

Solution :
To solve the issue add **#if UNITY_IOS** at the start of the script and **#endif** on the end so it will only work when IOS module is installed.

**Comment by skyf0xx** [comment]
Confirmed - error shows up with v1.1.2 SDK and on a Unity that doesn't have iOS module installed.

**Comment by chaseeb** [comment]
@djaydino @hitwill Could one of you possibly create PR for this?

**Comment by hitwill** [comment]
@djaydino @chaseeb I'll create one tomorrow

**Comment by skyf0xx** [comment]
Refer to [PR#25](https://github.com/kinecosystem/kin-sdk-unity/pull/25) for suggested fix.
