### ISSUE TITLE
 Could not find com.github.kinecosystem.kin-sdk-android:kin-sdk-lib

### ISSUE THREAD

**Issue by ADEELHAMZA40** [kinecosystem/kin-sdk-unity#28]
when i try to build your given demo project for android i am getting this error kindly help me to resolve this issue 

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':launcher:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':launcher:debugRuntimeClasspath'.
   > Could not find com.github.kinecosystem.kin-sdk-android:kin-sdk-lib:1.0.5.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/kinecosystem/kin-sdk-android/kin-sdk-lib/1.0.5/kin-sdk-lib-1.0.5.pom
       - https://dl.google.com/dl/android/maven2/com/github/kinecosystem/kin-sdk-android/kin-sdk-lib/1.0.5/kin-sdk-lib-1.0.5.jar
       - https://jcenter.bintray.com/com/github/kinecosystem/kin-sdk-android/kin-sdk-lib/1.0.5/kin-sdk-lib-1.0.5.pom
       - https://jcenter.bintray.com/com/github/kinecosystem/kin-sdk-android/kin-sdk-lib/1.0.5/kin-sdk-lib-1.0.5.jar
       - file:/C:/Users/Brothers/Documents/GitHub/kinland/Temp/gradleOut/unityLibrary/libs/kin-sdk-lib-1.0.5.jar
       - file:/C:/Users/Brothers/Documents/GitHub/kinland/Temp/gradleOut/unityLibrary/libs/kin-sdk-lib.jar
     Required by:
         project :launcher > project :unityLibrary
   > Could not find com.github.kinecosystem.kin-sdk-android:kin-backup-and-restore-lib:1.0.5.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/kinecosystem/kin-sdk-android/kin-backup-and-restore-lib/1.0.5/kin-backup-and-restore-lib-1.0.5.pom
       - https://dl.google.com/dl/android/maven2/com/github/kinecosystem/kin-sdk-android/kin-backup-and-restore-lib/1.0.5/kin-backup-and-restore-lib-1.0.5.jar
       - https://jcenter.bintray.com/com/github/kinecosystem/kin-sdk-android/kin-backup-and-restore-lib/1.0.5/kin-backup-and-restore-lib-1.0.5.pom
       - https://jcenter.bintray.com/com/github/kinecosystem/kin-sdk-android/kin-backup-and-restore-lib/1.0.5/kin-backup-and-restore-lib-1.0.5.jar
       - file:/C:/Users/Brothers/Documents/GitHub/kinland/Temp/gradleOut/unityLibrary/libs/kin-backup-and-restore-lib-1.0.5.jar
       - file:/C:/Users/Brothers/Documents/GitHub/kinland/Temp/gradleOut/unityLibrary/libs/kin-backup-and-restore-lib.jar
     Required by:
         project :launcher > project :unityLibrary

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
]
stdout[

> Configure project :launcher
WARNING: The option 'android.enableR8' is deprecated and should not be used anymore.
It will be removed in a future version of the Android Gradle plugin, and will no longer allow you to disable R8.
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <3746c56c485a40cda2a56050de658f5e>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <3746c56c485a40cda2a56050de658f5e>:0)
UnityEditor.Android.Command.Run (System.String command, System.String args, System.String workingdir, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <3746c56c485a40cda2a56050de658f5e>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <3746c56c485a40cda2a56050de658f5e>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <3746c56c485a40cda2a56050de658f5e>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <3746c56c485a40cda2a56050de658f5e>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <3746c56c485a40cda2a56050de658f5e>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <3746c56c485a40cda2a56050de658f5e>:0)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.Android.PostProcessor.CancelPostProcess.AbortBuild (System.String title, System.String message, System.Exception ex) (at <3746c56c485a40cda2a56050de658f5e>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <3746c56c485a40cda2a56050de658f5e>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <3746c56c485a40cda2a56050de658f5e>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <3746c56c485a40cda2a56050de658f5e>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <bd45cfd5e8c2437da9b5cc29b19f336f>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

**Comment by ADEELHAMZA40** [comment]
if i build in unity 2018.4 then this error not appear but i want to build it in unity 2020.1.10 then this error occure

**Comment by arslanarshadd** [comment]
I am facing this error on 2018.4 and on even 2020
.2.1f1.
