### ISSUE TITLE
KinDemoScene  - onboarding bad request error, other api calls do not return errors, but just nulls

### ISSUE THREAD

**Issue by skyf0xx** [kinecosystem/kin-sdk-unity#4]
So I have downloaded the unity plugin and opened up the demo scene (no change in the code). I have also updated the gradle template according to the instructions.

However, when I try to run the scene, the connecting to service provider message does not change.
![image](https://user-images.githubusercontent.com/2501079/53808043-2b8ad180-3f8c-11e9-92f0-e4556d30f610.png)

This is true even with my firewall turned off, or building and running on a test android device.

Clicking create account does not generate any json, or return any error.

Clicking create account under onboarding shows a bad request error:
![image](https://user-images.githubusercontent.com/2501079/53808170-858b9700-3f8c-11e9-8c10-1733c65facba.png)

I have also posted the issue on [stackoverflow](https://stackoverflow.com/questions/54996095/unity-kin-plugin-bad-request), which has more details on custom code I wrote to test the plugin, with similar results.

I have attached the gradle file i'm using in txt format for reference....
[mainTemplate.gradle.txt](https://github.com/kinecosystem/kin-sdk-unity/files/2931079/mainTemplate.gradle.txt)

**Comment by skyf0xx** [comment]
I believe the Bad Request error is being returned by the [friendbot](http://friendbot-testnet.kininfrastructure.com/?addr=)

![image](https://user-images.githubusercontent.com/2501079/53809103-e87e2d80-3f8e-11e9-8d0e-ae079aa5c617.png)

Meaning the problem is, the public address being generated is null (without an error being raised). When this null is passed to the friendbot, it comes back as a bad request.

**Comment by skyf0xx** [comment]
The generated public address is initially fine when AddAccount is called.

![image](https://user-images.githubusercontent.com/2501079/53809391-98ec3180-3f8f-11e9-9580-2b1afe812cef.png)

However, when it's passed into the KinAccount class, it magically becomes null

**Comment by skyf0xx** [comment]
From there onwards, calling GetPublicAddress returns nulls

**Comment by Ronserruya** [comment]
Hey, is this still reproducible?
We had some issues on the blockchain testnet today that caused 400s on friendbot requests.

**Comment by skyf0xx** [comment]
The problem is still there. I have traced it down to the function: GetPublicAddress().

The account_id is being created and preserved through out the code without a problem. However, when it gets to GetPublicAddress(), NativeBridge returns a string of null. This null string is what is causing more errors downstream.

![image](https://user-images.githubusercontent.com/2501079/53843626-0de65800-3fde-11e9-96aa-5aeedd219827.png)

It seems the problem is coming from NativeBridge

**Comment by skyf0xx** [comment]
Is it supposed to be like this? (first time encountering NativeBridge)

![image](https://user-images.githubusercontent.com/2501079/53844268-235c8180-3fe0-11e9-9bd4-7c8942cabd39.png)

When I run the code in debug mode, this is the NativeBridge class it is loading...and this class is returning the null for the public address. I wonder if it's carriage returns between mac and pc that are causing the wrong NativeBridge class to be selected? (I am running on windows). 

Just shooting in the dark here, since I've never used NativeBridge classes before.

**Comment by Ronserruya** [comment]
Are you trying to run your code on an android device? or natively on your PC?

The [NativeBridge.Editor.cs](https://github.com/kinecosystem/kin-sdk-unity/blob/master/Kin%20Unity/Assets/Kin/Core/NativeBinding/NativeBridge.Editor.cs) file is just a place order for unsupported platforms.

```
	/// <summary>
	/// empty implemention of the INativeBridge interface for use in the editor and on unsupported platforms.
	/// </summary>
```

If you are running on Android, this is the file that should be loaded [NativeBridge.Android.cs](https://github.com/kinecosystem/kin-sdk-unity/blob/master/Kin%20Unity/Assets/Kin/Core/NativeBinding/NativeBridge.Android.cs)

**Comment by skyf0xx** [comment]
Thanks for this! I was running it on the PC, which now makes sense...So I guess that solves the above problems...(That was definitely the issue)

However, compile it and running it on an android device now brings up the following problem:
![image](https://user-images.githubusercontent.com/2501079/53866539-bf13df00-402c-11e9-89ff-5111475b99ef.png)

**Comment by skyf0xx** [comment]
All sorted! 
So for anyone who has problems in future:
1. Run on android device or emulator (not on editor)
2. Disable minify (proguard) in player settings

Thanks @Ronserruya for the help! I would suggest adding this to a trouble-shooting section?

**Comment by Ronserruya** [comment]
@prime31 Hey Mike, is this expected that users will need to disable proguard?

**Comment by prime31** [comment]
It’s always possible proguard can get a little strip happy, especially when using the JNI. I’ll stick a proguard file in there in the next update that just preserves everyone always.
