### ISSUE TITLE
account.Getbalance exception does not bubble upwards to the Unity SDK

### ISSUE THREAD

**Issue by skyf0xx** [kinecosystem/kin-sdk-unity#6]
I noticed that the function below, when called before an account is funded, just dies silently.

![image](https://user-images.githubusercontent.com/2501079/54086140-6c665a00-4381-11e9-896d-ba1f2ec8c4ea.png)

However, when you look at the logs in android, you get this:
![image](https://user-images.githubusercontent.com/2501079/54086205-4c836600-4382-11e9-9a7c-44c744a2bfbb.png)

So it seems that the exception doesn't bubble all the way upwards?

**Comment by Ronserruya** [comment]
Thank for reporting, looks like this happens because the [android SDK throws an "AccountNotFoundException"](https://github.com/kinecosystem/kin-sdk-android/blob/af38e14a6999c939a68704ab4eab04b973d294d2/kin-sdk/src/main/java/kin/sdk/AccountInfoRetriever.java#L49), 
[but the Unity bridge only expects "OperationFailedException"](https://github.com/kinecosystem/kin-sdk-unity/blob/master/Kin%20Android/app/src/main/java/kin/unity/KinPlugin.java#L233)

I will update here once we fix it :+1:

**Comment by Ronserruya** [comment]
Actually "AccountNotFoundException" extends "OperationFailedException" so it should have worked.
@prime31 Any idea?

**Comment by skyf0xx** [comment]
I'll run some more tests and see if I can get to the bottom of it

**Comment by prime31** [comment]
I can't seem to repro this. Steps followed:

- create KinClient: `var client = new KinClient( Environment.Test, "test" );`
- add an account: `var account = client.AddAccount();`
- check balance:

```csharp
account.GetBalance( ( ex, balance ) =>
{
	if( ex == null )
		Debug.Log( "Balance: " + balance );
	else
		Debug.LogError( "Get Balance Failed. " + ex );
});
```

Results in the completion handler firing with the proper Exception which logged looks like:

```
03-10 17:05:17.859 22597 22904 E Unity   : Get Balance Failed. Message: Account GBKNHCIICJ7I7U4QUCFGU2JJXRM3RAEW35GPSROKIRC4S5ATMQQOJING was not found, NativeType: AccountNotFoundException, ErrorCode: 0, AccountId: ybbrnaa3m48
03-10 17:05:17.859 22597 22904 E Unity   : UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
03-10 17:05:17.859 22597 22904 E Unity   : UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
03-10 17:05:17.859 22597 22904 E Unity   : UnityEngine.Logger:Log(LogType, Object)
03-10 17:05:17.859 22597 22904 E Unity   : UnityEngine.Debug:LogError(Object)
03-10 17:05:17.859 22597 22904 E Unity   : Kin.KinDemoUI:<OnRightColumnGUI>m__3(KinException, Decimal) (at /Users/desaro/Desktop/Kin/Kin Unity/Assets/Kin/Demo/KinDemoUI.cs:221)
03-10 17:05:17.859 22597 22904 E Unity   : Kin.Utils:FireActionInDict(Dictionary`2, String, KinException, Decimal) (at /Users/desaro/Desktop/Kin/Kin Unity/Assets/Kin/Core/DTOs/Utils.cs:104)
03-10 17:05:17.859 22597 22904 E Unity   : Kin.KinManager:GetBalanceFailed(String) (at /Users/desaro/Desktop/Kin/Kin Unity/Assets/Kin/Core/KinManager.cs:145)
```

**Comment by skyf0xx** [comment]
This was a problem with my code. I had wrapped the above block of code in a function. Naturally, when the wrapper function was called, account.Getbalance would run, but then immediately get thrown out of scope, and be unable log any data.

Resolved by creating a separate callback function, and passing this callback into account.Getbalance.

To illustrate:
Instead of:

    function _GetBalance(){
	    account.GetBalance( ( ex, balance ) =>
	    {
		if( ex == null )
			Debug.Log( "Balance: " + balance );
		else
			Debug.LogError( "Get Balance Failed. " + ex );
	    });
	}
Simply this:
	
    function _GetBalance(){	
		account.GetBalance(CallbackFunction)
	}
