### ISSUE TITLE
Where can we see testnet transactions?

### ISSUE THREAD

**Issue by skyf0xx** [kinecosystem/kin-sdk-unity#7]
Once we have created some test transactions on the SDK - where can we see them on the blockchain? (Is this the stellar testnet, or a specific Kin testnet?

I tried http://laboratory-testnet.kininfrastructure.com/#explorer?network=test

But that was down (8:04 am 12 March 2019 (UTC))

Which explorer should we use?

**Comment by skyf0xx** [comment]
Found it: https://laboratory-beta.kininfrastructure.com/#explorer?resource=payments

Also suggested a pull request in the documentation, to display it.

**Comment by Ronserruya** [comment]
We just launched this block explorer yesterday:
https://www.kin.org/blockchainExplorer
